### ISSUE TITLE
overwrite passwd

### ISSUE THREAD

**Issue by panosdim** [excalibur1234/pacui#18]
Hi, 
I tried option 2, Maintenance system and then i choose overwrite in passwd and shadowd and now i can't login. 

  Enter number or marked letter(s)      -   00   Help   -    0   Quit 
2

choosing fastest mirror ...

searching orphans ...

sudo pacdiff ...
==> pacnew file found for /etc/group
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] o
'/etc/group.pacnew' -> '/etc/group'
==> pacnew file found for /etc/passwd
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] o
'/etc/passwd.pacnew' -> '/etc/passwd'
==> pacnew file found for /etc/shadow
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] o
'/etc/shadow.pacnew' -> '/etc/shadow'
==> pacnew file found for /etc/gshadow
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] o
'/etc/gshadow.pacnew' -> '/etc/gshadow'

sudo: unknown uid 1001: who are you?

checking consistency of local repository ...

checking AUR packages ...

cleaning systemd log files ...
sudo: unknown uid 1001: who are you?

cleaning package cache ...
sudo: unknown uid 1001: who are you?

sudo: unknown uid 1001: who are you?

sudo pacman-optimize ...
sudo: unknown uid 1001: who are you?

 System maintenance finished. To return to PacUI press ENTER

**Comment by thefallenrat** [comment]
> then i choose overwrite in passwd and shadowd and now i can't login.

That's because those `pacnew` files doesn't contain your account password information and such. And by replacing with it, you have now lost all your account password etc ...

If you have backup, I suggest to restore your system it. If you don't have one, re-install is highly recommended

I suggest in the next time you have `pacnew`, read up in forums and ask others or use `diff` `vimdiff` or `meld` to compare and decide from it....

This is hardly a pacui's fault

---
Discussions related to those specific `pacnew` files : 

https://forum.manjaro.org/t/unstable-updates-create-new-etc-passwd-pacnew-etc/26027

https://forum.manjaro.org/t/stable-update-2017-06-22-calamares-thus-cinnamon-gstreamer-mesa/26316/6?u=thefallenrat

https://forum.manjaro.org/t/stable-update-2017-06-18-kernels-plasma-kde-apps-firefox-thunderbird-mesa/26086/22?u=thefallenrat

https://forum.manjaro.org/t/stable-update-2017-06-18-kernels-plasma-kde-apps-firefox-thunderbird-mesa/26086/88?u=thefallenrat

**Comment by panosdim** [comment]
I restored the files from a backup and everything is ok now.
Thanks.

**Comment by excalibur1234** [comment]
thanks @thefallenrat for answering this question. i was busy with real life the last week.

i have just added more test to the help page including a warning: 690dcc553a870d0e7b57fd84680a9545423d0e45

for a short time, i was tempted to mark option 2 red. but then, i would also need to mark the options red: 1, 3, 4, ,9, 10, 11, 17. then, almost all of pacui's options are red!

@panosdim, is there something pacui can improve to prevent others from the same situation you were in?
pacui's option 2 shows you a (short) overview of all lines, which are different in your .pacnew and config file. i could include also non-different lines (3 lines above and below the different line) in that overview. do you think this could help?

**Comment by panosdim** [comment]
Maybe you can show an alert in option 2 that if you don't know what you are
doing you may destroy your OS.

**Comment by excalibur1234** [comment]
> Maybe you can show an alert in option 2 that if you don't know what you are doing you may destroy your OS.

i can understand your point of view. you want to prevent other users from making the same mistake as you. there are many more dangers lurking in rolling release linux system as i have tried to mention in my last post:

- option 1 should be red, because updates can always break your system (or at least xorg - this has happened multiple times to me).

- option 2 should be red, because removing orphan packages can destroy your system, if those dependencies are important, but only marked as "optional" or if the user has changed their dependency to an unimportant package.

- option 3 should be red, because the maintainer of a package could insert malicious code.

- option 4 should be red (see option 2).

- option 9 should be red, because rolling back a single package (without rolling back all its dependencies) can break your system

- option 10 should be red (see option 1 and 3)

- option 11 should be red, because editing config files can destroy your system

- option 17 should be red (see option 3)

this means that EVERY option in pacui, which changes ANYTHING in your system should be red (i.e. marked as dangerous)!
if almost everything is marked red, the red mark looses its meaning.


this is the statement on pacui's front github page:

> PacUI is aimed at experienced/intermediate/advanced users of Manjaro or Arch Linux, who have at least basic knowledge of the structure of their Linux system and how Pacman and Pacaur/Yaourt work.

if people do not know what they are doing (and do not read the help page and have no backup), i can not help them.
(this is not meant as an insult, but a mere observation. i have done the same as you did, because i was curious what would happen. i had to reset my virtual machine in order to recover.)

if i start to display warnings in pacui, i should display ALL possible things, which can break your system. in that case, the help page could be removed, but the output of pacui would be extremely cluttered. experienced users would be annoyed by that and beginners would be afraid to do anything at all. this is the reason why i chose to create an extensive help page instead.

**Comment by excalibur1234** [comment]
please reopen this issue, if you have something substantial to contribute.
