### ISSUE TITLE
Maintain system option

### ISSUE THREAD

**Issue by fhdk** [excalibur1234/pacui#23]
When only `packer` installed an error is thrown

    searching orphans ...
    /usr/bin/pacui: line 82: yaourt: command not found

**Comment by excalibur1234** [comment]
yes, this is the intended behavior.

pacui requires pacman and one of the following AUR helpers:
- pacaur (used by default, if yaourt is installed, too) 
- yaourt

(please look at the optional dependencies of the pacui package!)

if you do not have pacaur installed, it tries to use yaourt commands, because it requires one of the above mentioned AUR helpers.

if you want to keep using packer, you can manually execute the commands as listed here:
https://github.com/excalibur1234/pacui/blob/master/pacui#L1203
(instead of "yaourt -Qdt" use "sudo pacman -Rsn $(pacman -Qqdt)".

**Comment by excalibur1234** [comment]
if you are determined to use `packer` exclusively, you can do a pull request, which adds support for `packer`.
look for the code line
`if [[ ! -e /usr/bin/pacaur ]] `
which is used to filter the used AUR helper tool.

**Comment by fhdk** [comment]
I am not - pacaur is probably fine - thought I was reporting something new.

**Comment by excalibur1234** [comment]
no problem.
if you are ever in doubt again, feel free to open another issue.
