### ISSUE TITLE
new option: what about w3m to forum updates?

### ISSUE THREAD

**Issue by freed00m** [excalibur1234/pacui#33]
Hi,

Just an idea, what about terminal browser to view latest update forums?

Just w3m without images looks great on manjaro forumsand if user won't have w3m installed or uses non manjaro distro, the option would not be shown? Or alternative cli browsers and forums could be added later.
```
w3m -o auto_image=FALSE https://forum.manjaro.org/c/announcements/stable-updates/l/latest
```

**Comment by excalibur1234** [comment]
i have thought about your idea for a while.
i even installed w3m and elinks. i have used w3m before and know it a little bit. elinks was new to me, but i think it is more intuitive: pressing ESC for menu is so nice!

i am against it, because such an option would only wrap a rather short command into a completely new pacui command.

people, who want to make their own "update" function, could simply add an alias to their shell config file, e.g.:

> `alias mu='w3m -o auto_image=FALSE https://forum.manjaro.org/c/announcements/stable-updates/l/latest'`

**Comment by excalibur1234** [comment]
i will close this as "won't fix", but feel free to reopen this issue, if you have an idea for a new pacui option, which cannot easily made with aliases.
