### ISSUE TITLE
"unbound variable" error when editing config files

### ISSUE THREAD

**Issue by DrDoctor13** [excalibur1234/pacui#38]
When trying to edit config files (command 11), pacui throws this error then terminates.

`/usr/bin/pacui: line 1265: XDG_CONFIG_DIRS: unbound variable
`

**Comment by excalibur1234** [comment]
thanks for the bug report.

this error appeared is present in version 1.9.2 of pacui, but was resolved in version 1.10.
it should be never appear in version 1.10.1, because bash strict mode was completely disabled.

if you are using manjaro and want to use a bug-free version of pacui, you can switch to the unstable branch or install pacui from the AUR. otherwise, just wait until pacui 1.10.1 has reached the stable branch.

**Comment by DrDoctor13** [comment]
I just checked and I am using 1.9.2 on Manjaro. I'll wait for their next stable update and report back if the bug persists or not.

**Comment by excalibur1234** [comment]
please reopen this issue, if it happens again.
