### ISSUE TITLE
Shortened package names mess up alignment

### ISSUE THREAD

**Issue by Morganamilo** [excalibur1234/pacui#39]
Version: r859.2819ba8-1

![image](https://user-images.githubusercontent.com/16593899/39610719-2fcd3ad6-4f4a-11e8-9e69-05232da4a00f.png)

Here you can see the package `adobe-source-code-pro-fonts` has been shortened to `..o-fonts`. The alignment appears to still take the old length into account. So the 15 odd character of space saved causes the description to slide to the left 15 odd characters.

**Comment by excalibur1234** [comment]
you have filtered your list of packages by typing "e". as you can see the "e" in "environment" is highlighted in the description of the adobe-source-code-pro-fonts package.
because the "e" in "environment" got highlighted, fzf tries to display the highlighted part which means it has to move "adobe-source-code-pro-fonts" to the left.

this is not a messed up alignment, but intentional!
you can check this by searching for "adobe-" and you see "adobe-source-code-pro-fonts" being aligned perfectly.

if you want to change fzf's way of searching (e.g. no fuzzy matching), you can do it.

**Comment by Morganamilo** [comment]
Huh okay then, my opinion is still that it looks a bit out of place. It does at least make sense as to why this happens now. Thanks for explaining.

**Comment by excalibur1234** [comment]
i am a little puzzled, why fzf's "fuzzy search" finds the "e" in "environment" and not the "e" in "adobe" (which is the first "e" in that line).

it has found the "e" in "android-udev" and not the last "e" in that line. 

this behavior is kind of inconsistent and i do not like it. but fuzzy search becomes useful, when you start to search for more than a couple of letters...
