### ISSUE TITLE
Fix Pacman Errors throws errors

### ISSUE THREAD

**Issue by seafox** [excalibur1234/pacui#41]
line 42 is pretty standard: `SigLevel = Required DatabaseOptional`

What's the reason for those red errors?

![pacui-fix-pacman-42](https://user-images.githubusercontent.com/9025690/42724577-9968ff8c-877d-11e8-9cc7-1dac297579a9.png)

**Comment by excalibur1234** [comment]
i assume you are testing "pacui" and not "pacui-git".
if you use "pacui-git", you are using an old version. please update!

the error you are experiencing was fixed in https://github.com/excalibur1234/pacui/commit/7191902efd87f3dc67b1dcfae71a21a8a4f9a682
i am not sure, where it comes from. probably pacman 5.1 has changed something....

**Comment by seafox** [comment]
Your assumed correct. The mentioned errors gone with git version, can be closed now.
Maybe one notice is suppressing the error marked in yellow below, if it's easy to do.

![pacui-git-10](https://user-images.githubusercontent.com/9025690/42732731-09bfea46-882f-11e8-9a15-63fac9df912c.png)

**Comment by excalibur1234** [comment]
i never thought to suppress these non-critical error. thanks for the tip.

this is fixed in e0b668b40b55b5922bff4a3e16cb1e439e569725
