### ISSUE TITLE
pacui not able to show package information

### ISSUE THREAD

**Issue by zany130** [excalibur1234/pacui#53]
pacui is unable to show packag information and gives a syntax error
![Screenshot_20200221_131004](https://user-images.githubusercontent.com/25832539/75059713-883c1080-54ab-11ea-8bc1-a93229c4601d.png)

**Comment by excalibur1234** [comment]
i am in the process of getting the next version of pacui ready.
it takes a little longer than i thought.

can you please test the latest development version of pacui as described here:
https://github.com/excalibur1234/pacui#execute-without-prior-installation
i did fix a bug like this in that version.

if the error still occurs, can you please tell me, which AUR helper you are using?

**Comment by zany130** [comment]
Ok ill try it when I get home. I'm using yay.

**Comment by zany130** [comment]
the issue is still present even in that version

**Comment by excalibur1234** [comment]
i have installed yay and removed pikaur from my system.

this is what i get with the latest pacui version:
https://i.imgur.com/61jdHaY.png

in you screenshot above, i noticed the non-dotted outline of the package preview. the latest version of pacui does not have that anymore (see in my screenshot).
therefore i am not sure, whether you actually used the latest version for your latest tests.

these command should make that you (temporarily) use the latest version of pacui:
```
wget https://raw.githubusercontent.com/excalibur1234/pacui/master/pacui
chmod +x pacui
./pacui
```

also, please do a "pacui m" before testing again.
can you see the dotted outline of package preview in your tests?

**Comment by zany130** [comment]
that's what I did last time minus the pacui m here I did pacui m the downloaded and ran the script again 
![Screenshot_20200223_110936](https://user-images.githubusercontent.com/25832539/75115516-2c00fa00-562d-11ea-9fa4-44ee60afa32f.png)

**Comment by seafox** [comment]
I can confirm it shows pkg info properly:
![image](https://user-images.githubusercontent.com/9025690/75115422-50250100-5656-11ea-92de-6b85a9688d01.png)

One minor UX wish would be... actually two:
1. `read -n1 -rsp "...exit..."` argument will take a single key press and also eat echo, so the pressed key wouldn't be passed into console interface to puzzle...
2. Although other views have intuitive exits by pressing Esc button there is no such option on default view.
Both wishes are somehow reflected below :)
![image](https://user-images.githubusercontent.com/9025690/75115554-7dbe7a00-5657-11ea-9d8c-7d73c129cb21.png)

Maybe it's time to try to re-submit this handy program to AUR again...

**Comment by seafox** [comment]
Visually spotted yet another lovely couple :)
Plasma konsole, self-explanatory:
![image](https://user-images.githubusercontent.com/9025690/75115863-a431e480-565a-11ea-98df-964584398e43.png)

**Comment by excalibur1234** [comment]
@zany130 : 
sorry, but i cannot reproduce you problem. i have tested manjaro and arch linux both with bash and zsh shell.
i tested pikaur and yay.
in every case, pacui works fine.

i have even tested in on manjaro 32bit, because there were problems in the past with it. however, there is a completely different bug, which prevents me from seeing the list of available packages (that problem is related to an outdated version of fzf).

the error message indicates, that the following bash code does not work on your system (this code gets executed by fzf):
`if [[ $(comm -12 <(echo {yay}) <(sort /tmp/pacui-list-install-groups)) ]]; then echo "impossible"; else echo "works"; fi`
you could try to run this code in your bash or zsh shell and give me the output. we could do this bach and forth a dozen of times, which gets tiresome really fast.

is there anything out of the ordinary about your system, pacui, or fzf?
if this is the case, i can do further tests.

**Comment by zany130** [comment]
running that command gives this 
```
if [[ $(comm -12 <(echo {yay}) <(sort /tmp/pacui-list-install-groups)) ]]; then echo "impossible"; else echo "works"; fi
sort: cannot read: /tmp/pacui-list-install-groups: No such file or directory
works
```

**Comment by excalibur1234** [comment]
during operation, pacui should create multiple files in your /tmp directory.

so, if you have opened pacui "install packages" since your computer has started, the file (and other files with names starting with "pacui-") `/tmp/pacui-list-install-groups` should have been created on your system.

but on the bright side, the bash command itself runs fine.

**Comment by excalibur1234** [comment]
next, you could test
`pacman -Qq |  fzf --preview ' if [[ $(comm -12 <(echo {1}) <(sort /tmp/pacui-list-install-groups)) ]]; then echo "impossible"; else echo "works"; fi '`
(quit fzf with CTRL+C)

but even if that works, it does not tell me much.

**Comment by zany130** [comment]
it gives this
![Screenshot_20200223_135318](https://user-images.githubusercontent.com/25832539/75117935-ec91d800-5643-11ea-8b20-3d9d71c54af3.png)

**Comment by excalibur1234** [comment]
@seafox 
thx for confirming that this problem is hard to reproduce.

there are multiple thing you talk about (as i understand you):

1. i have tested (and actually use in a couple of places) "read -n1". i have actually made a modification in the past that enabled pacui to be quit by a single press of the ESC button (see https://forum.manjaro.org/t/pacui-bash-script-providing-advanced-pacman-and-yay-pikaur-aurman-pakku-trizen-pacaur-functionality-in-a-simple-ui/677/521). but it had drawbacks.

2. in order to start pacui's options with a single button press, i would throw out (or heavily modify) the way to start these options. multi-digit/multi-letter arguments would need to go. all users would need to relearn their muscle memory, because options will start mostly with a completely different shortuct/key letter/key number. i try to avoid that.

     i am bothered by this behavior, too. therefore, instead of typing "pacui" and then "i" and "ENTER", i use "pacui i", which is much faster. if you use an option often, i recommend to do the same.

3. pressing ESC and ENTER quits pacui as well (but the output of ESC looks ugly).

if you want to talk about this in earnest, please open a new issue.

**Comment by excalibur1234** [comment]
@zany130 
which version of fzf are you using?
which shell are you using?

this looks like a totally different behavior of fzf than on my (and seafox') system.

the error says that fzf tries to execute a command in the "sh" shell, which means that "sh" is set as your startup shell.

if your startup shell is bash or zsh, the problem should be gone.

pacui runs explicitly in bash, even if your shell is different. unfortunately, i do not know how to make fzf to run its preview code in bash.
therefore, pacui requires bash and does not work with "sh" shell.

p.s.: you can change your startup shell in linux with the "chsh" command.

**Comment by zany130** [comment]
no, I use the bash shell for my system but I think an update manjaro did mess something up as I restored before this update and pacui works perfectly (the one from the repos)

**Comment by zany130** [comment]
well I think it was something that went wrong with the update it idk as it works perfectly fine now will close

**Comment by zany130** [comment]
this issue sort of came back have a look 
![Screenshot_20200228_202813](https://user-images.githubusercontent.com/25832539/75598348-f0b95d80-5a68-11ea-9a13-cc1f66bae5d3.png)

**Comment by excalibur1234** [comment]
as i understand my code, not even the first problem you had should have not occurred. the first and second line of the code clearly defines BASH as shell for pacui itself and every process it starts (i.e. fzf):
https://github.com/excalibur1234/pacui/blob/master/pacui#L2

my tests on manjaro and arch linux (using different startup shells in both cases) cannot reproduce your problem and in fact even show that BASH is always used for pacui and fzf as i have intended (even if the startup shell and shell that starts pacui is different).
 
could your problem be related to your manjaro version/install?
if you tell me, what manjaro ISO you have used for your last install, i could install it in a VM as well and test pacui there...

**Comment by zany130** [comment]
i think it was a bug in some package or something as  i recently switched to the testing branch of manjaro as i was having issues with stable holding packes back to long and ever since then pacui has worked without issue. I wanted to make sure the issue was solve this time but its been about a week since I switched and everything works fine. thanks for taking the time to try and reproduce the issue and all  the work you have put in thanks to your tool im not afraid of terminal based package managment in arch lol
